name: update-news
on:
  schedule: [{ cron: '*/15 * * * *' }]
jobs:
  main:
    runs-on: ubuntu-latest
    env:
      NEWS_FEED_URL: https://www.pref.tottori.lg.jp/services/rdf/rss10/589717.xml
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GIT_TOKEN }}
      - run: |
          curl \
            -sL "https://api.rss2json.com/v1/api.json?rss_url=${NEWS_FEED_URL}" \
          | jq '{
            newsItems: [
              .items[:3][]
              | {
                date: "\(.pubDate | sub(" ";"T"))Z",
                url:  .link,
                text: .title
              }
            ]
          }' \
          | ruby \
            -rcgi \
            -pe '$_=CGI.unescape_html($_)' \
          | tee data/news.json
      - id: git_status
        run: echo "::set-output name=mod::$(git status --porcelain)"
      - if: steps.git_status.outputs.mod != ''
        run: |
          git add data/news.json \
          && git -c "user.name=${GITHUB_ACTOR}" -c "user.email=${GITHUB_ACTOR}@users.noreply.github.com" commit -m update-news \
          && git push origin HEAD
